package himedia.project.entity;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import himedia.project.entity.Board;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/*
 * create table board(
   id bigint generated by default as identity,
   title varchar (50),
   content varchar (500),
   writer varchar(20),
   hits bigint,
   create_date datetime,
   update_date datetime,
   primary key(id)
);
 */

@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity
public class Board {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Long id;
	
	@Column(name = "title")
	private String title;
	@Column(name = "content")
	private String content;
	@Column(name = "writer")
	private String writer;
	@Column(name = "hits")
	private Long hits;
	@Column(name = "create_date")
	private LocalDateTime createDate = LocalDateTime.now();
	@Column(name = "update_date")
	private LocalDateTime updateDate;
	
	private String filename;
	private String filepath;
	
	@Builder
	public Board(String title, String content, String writer, Long hits) {
		this.title = title;
		this.content = content;
		this.writer = writer;
		this.hits = hits;
	}
	
//	public void update(String title, String content, String writer) {
//		this.title = title;
//		this.content = content;
//		this.writer = writer;
//		this.updateDate = LocalDateTime.now();
//	}
	
//	public void increaseHits() {
//		this.hits++;
//	}
	
}
