package himedia.project.entity;

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/*
 * create table pet(
   id bigint generated by default as identity,
   reservate_date date,
   userid varchar (25),
   pet_name varchar (25),
   pet_age int,
   pet_gender enum ('male', 'female'),
   phone varchar (15),
   address varchar (50),
   content varchar (500),
   primary key(id)
);
 */

@Getter
@NoArgsConstructor
@Entity
@Table(name = "PET")
public class Pet {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	private LocalDate reservateDate;
	@Column(name = "userid")
	private String userId;
	private String petName;
	private int petAge;
	@Enumerated(EnumType.STRING)
	@Column(name = "pet_gender")
	private Gender gender;
	private String phone;
	private String address;
	private String content;
	
	@Builder
	public Pet(LocalDate reservateDate, String userId, String petName, int petAge,
			Gender gender, String phone, String address, String content) {
		this.reservateDate = reservateDate;
		this.userId = userId;
		this.petName = petName;
		this.petAge = petAge;
		this.gender = gender;
		this.phone = phone;
		this.address = address;
		this.content = content;
	}
	
}
